import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import QueryProvider from "@/lib/providers/QueryProvider";
 
const inter = Inter({ subsets: ['latin'] });
 
export const metadata: Metadata = {
	title: "Test TanStack",
	description: "Generated by create next app",
};
 
export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>
				<QueryProvider>
					{children}
				</QueryProvider>
			</body>
		</html>
	);
}